services:
  - type: web
    name: makeup-bot
    env: python
    runtime: 3.10.9
    buildCommand: ""          # ничего не компилируем
    startCommand: bash start.sh
    plan: free
    autoDeploy: true
