services:
  - type: web
    name: makeup-bot
    env: python
    runtime: 3.10.9
    buildCommand: ""       # сборка не нужна, всё в start.sh
    startCommand: bash start.sh
    plan: free
    autoDeploy: true
