services:
  - type: web
    name: makeup-bot
    env: python
    runtime: python             # <- без дефиса спереди!
    buildCommand: ""            # <- оставляем пустым
    startCommand: bash start.sh # <- обязательно для python
    plan: free
    autoDeploy: true
